# softmax function test


In [3]:
# Key を定義
import numpy as np
K = np.array([[0,1,2,3], 
              [3,2,1,0],
              [4,4,4,4],
              [1,0,1,0],
              [1,4,3,2]
              ])

Q = K

print('K')
print(K)
print()

print('Q')
print(Q)

K
[[0 1 2 3]
 [3 2 1 0]
 [4 4 4 4]
 [1 0 1 0]
 [1 4 3 2]]

Q
[[0 1 2 3]
 [3 2 1 0]
 [4 4 4 4]
 [1 0 1 0]
 [1 4 3 2]]


In [4]:
def standard(matrix):
    import numpy as np
    output = []
    temp_max = matrix.max()
    temp_min = matrix.min()
    for list in matrix:
        for val in list:
            temp= (val-temp_min)/(temp_max-temp_min)
            output.append(temp)
    
    output = np.array(output)
    output = output.reshape(matrix.shape)
    return output

In [5]:
print('OLD')
print(K)

print()
print('NEW')
K_new=standard(K)
print(K_new)

OLD
[[0 1 2 3]
 [3 2 1 0]
 [4 4 4 4]
 [1 0 1 0]
 [1 4 3 2]]

NEW
[[0.   0.25 0.5  0.75]
 [0.75 0.5  0.25 0.  ]
 [1.   1.   1.   1.  ]
 [0.25 0.   0.25 0.  ]
 [0.25 1.   0.75 0.5 ]]


In [6]:
# Qと（Kの転置）の内積をKのサイズ(=5)の平方根で割る．
dot_product = np.dot(Q,K.T)
print('dot_product')
print(dot_product)
print()

dot_product = dot_product/np.sqrt((K).shape[0])
print('devided by the sqrt(len of matrix)')
print(dot_product)
print()

dot_product = standard(dot_product)
print("standard")
print(dot_product)


dot_product
[[14  4 24  2 16]
 [ 4 14 24  4 14]
 [24 24 64  8 40]
 [ 2  4  8  2  4]
 [16 14 40  4 30]]

devided by the sqrt(len of matrix)
[[ 6.26099034  1.78885438 10.73312629  0.89442719  7.15541753]
 [ 1.78885438  6.26099034 10.73312629  1.78885438  6.26099034]
 [10.73312629 10.73312629 28.62167011  3.57770876 17.88854382]
 [ 0.89442719  1.78885438  3.57770876  0.89442719  1.78885438]
 [ 7.15541753  6.26099034 17.88854382  1.78885438 13.41640786]]

standard
[[0.19354839 0.03225806 0.35483871 0.         0.22580645]
 [0.03225806 0.19354839 0.35483871 0.03225806 0.19354839]
 [0.35483871 0.35483871 1.         0.09677419 0.61290323]
 [0.         0.03225806 0.09677419 0.         0.03225806]
 [0.22580645 0.19354839 0.61290323 0.03225806 0.4516129 ]]


In [7]:
import numpy as np
def softmax(list):
    output = []
    bunbo = 0
    for val in list:
        bunbo += np.exp(val) 
    print(f'分母：{bunbo}')
    for val in list:
        bunshi=np.exp(val)
        output.append(bunshi/bunbo)
        print(f'x: {val}\t分子: {bunshi}')
    return output


In [8]:
softmax_output = softmax(dot_product)

分母：[5.92561581 5.91861485 8.51757706 5.16717959 6.91629128]
x: [0.19354839 0.03225806 0.35483871 0.         0.22580645]	分子: [1.21354811 1.032784   1.42595064 1.         1.25333306]
x: [0.03225806 0.19354839 0.35483871 0.03225806 0.19354839]	分子: [1.032784   1.21354811 1.42595064 1.032784   1.21354811]
x: [0.35483871 0.35483871 1.         0.09677419 0.61290323]	分子: [1.42595064 1.42595064 2.71828183 1.10161159 1.84578235]
x: [0.         0.03225806 0.09677419 0.         0.03225806]	分子: [1.         1.032784   1.10161159 1.         1.032784  ]
x: [0.22580645 0.19354839 0.61290323 0.03225806 0.4516129 ]	分子: [1.25333306 1.21354811 1.84578235 1.032784   1.57084376]


In [9]:
type(softmax_output)

list

In [10]:
print(softmax_output)
print(sum(softmax_output))

[array([0.20479696, 0.17449758, 0.16741271, 0.19352917, 0.18121462]), array([0.17429142, 0.20503921, 0.16741271, 0.19987383, 0.17546226]), array([0.24064176, 0.24092641, 0.31913792, 0.21319398, 0.26687458]), array([0.16875883, 0.17449758, 0.12933392, 0.19352917, 0.14932627]), array([0.21151102, 0.20503921, 0.21670275, 0.19987383, 0.22712227])]
[1. 1. 1. 1. 1.]


In [11]:
ans=np.dot(softmax_output,K)
print(ans)
print()

print('K')
print(K)
print()

[[1.56788738 1.94830142 1.99091536 1.64647094]
 [1.66010455 1.95586972 1.9495335  1.54344962]
 [2.47939948 3.0665446  3.01257935 2.53222614]
 [1.38368386 1.63239475 1.6708589  1.3222647 ]
 [1.90892472 2.3968895  2.37611288 1.9555886 ]]

K
[[0 1 2 3]
 [3 2 1 0]
 [4 4 4 4]
 [1 0 1 0]
 [1 4 3 2]]

